MAIL_USERNAME = 'patrickpwilliamson9@gmail.com'
MAIL_PASSWORD = 'Olayinka1'

ANALYTICS_GOOGLE_UA = 'foo'

SSTRIPE_SECRET_KEY = 'pk_test_51IWV8MKKBISTKSZXNSODH7mvRhj5uPkIHoFU1fPrtOXkLVWez5Fwy526Qb6ximsdxxfij9b0JYHmn44bhHyZrt2200zVMOhRm7'
STRIPE_PUBLISHABLE_KEY = 'sk_test_51IWV8MKKBISTKSZXn8bVHDuSPzMpkBooewRaVVQqKBfty8ebRygkBGl0iZMkePtEBUJLJKwqJotnQws0MRqNkGUX00ikA2m2P8'
